title: Portfolio
description: JHEA
url: https://narqulie.github.io
theme: minima
header_pages:
  - about.md
  - portfolio.md
  
  minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/narqulie/narqulie"}
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jheaminoff"}